name: vitcc_electrical_issues
description: A platform to raise electrical issues in VITCC.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  google_sign_in: ^5.2.1
  provider: ^6.0.2
  freezed_annotation: ^0.14.2
  flutter_spinkit: ^5.1.0
  form_field_validator: ^1.1.0

  # Change to original, once PR is merged.
  flutter_animator:
    git: https://github.com/rithviknishad/animator.git
  jiffy: ^5.0.0
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.17
  font_awesome_flutter: ^9.2.0
  syncfusion_flutter_datepicker: ^19.4.40
  cool_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.14.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/192.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        # - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        #   style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        # - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
        #   weight: 300
        #   style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        # - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        #   weight: 500
        #   style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        # - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        #   weight: 700
        #   style: italic
