name: vitcc_electrical_issues
description: A platform to raise electrical issues in VITCC.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # Remove if not used
  firebase_analytics: ^8.3.1
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  google_sign_in: ^5.1.0
  provider: ^6.0.0
  freezed_annotation: ^0.14.2
  flutter_spinkit: ^5.1.0
  fluttericon: ^2.0.0
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.14.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
