name: vitcc_electrical_issues
description: A platform to raise electrical complaints in VITCC.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # Remove if not used

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
