name: Flutter CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  flutter_version: "2.5.2"
  java_version: "12.x"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}

      - uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
      - run: flutter config --enable-web

      - run: flutter pub get
      - run: flutter pub run build_runner build

      - run: flutter build web --release --web-renderer html --tree-shake-icons --no-pub
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VITCC_ELECTRICAL_ISSUES }}"
          channelId: live
          projectId: vitcc-electrical-issues

      - run: echo $GOOGLE_SERVICES_JSON > ./android/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES }}

      - run: flutter build apk --release --split-per-abi --obfuscate --split-debug-info build/debug --shrink --tree-shake-icons --no-pub

      - run: rm ./android/app/google-services.json

      - uses: actions/upload-artifact@v1
        with:
          name: app-armeabi-v7a-release-apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@v1
        with:
          name: app-arm64-v8a-release-apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v1
        with:
          name: app-x86_64-release-apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
